### ISSUE TITLE
Nullfileformat as input

### ISSUE THREAD

**Issue by PepperJo** [zrlio/spark-nullio-fileformat#1]
When using NullFileFormat as input for the sql-benchmark tool it fails with the following exception:

17/11/03 14:55:21 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
17/11/03 14:55:22 INFO YarnSchedulerBackend$YarnDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (10.100.0.23:48976) with ID 7
17/11/03 14:55:22 INFO BlockManagerMasterEndpoint: Registering block manager flex23.zurich.ibm.com:35817 with 34.0 GB RAM, BlockManagerId(7, flex23.zurich.ibm.com, 35817, None)
17/11/03 14:55:22 INFO FileSourceStrategy: Pruning directories with: 
17/11/03 14:55:22 INFO FileSourceStrategy: Post-Scan Filters: 
17/11/03 14:55:22 INFO FileSourceStrategy: Output Data Schema: struct<intKey: int, randLong: bigint, randDouble: double, randFloat: float, randString: string ... 3 more fields>
17/11/03 14:55:22 INFO FileSourceScanExec: Pushed Filters: 
17/11/03 14:55:22 INFO FileOutputCommitter: File Output Committer Algorithm version is 1
17/11/03 14:55:22 INFO SQLHadoopMapReduceCommitProtocol: Using output committer class org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
17/11/03 14:55:22 INFO CodeGenerator: Code generated in 151.263389 ms
----- Null Source/Sink options (all lower caps) -----
path : /sql
17/11/03 14:55:22 ERROR FileFormatWriter: Aborting job null.
java.lang.Exception: Illegal option : path , valid options are: Set(payloadsize, intrange, inputrows, rowbuffersz, schema)
    at org.apache.spark.sql.NullFileFormat$$anonfun$buildReader$1.apply(NullFileFormat.scala:112)
    at org.apache.spark.sql.NullFileFormat$$anonfun$buildReader$1.apply(NullFileFormat.scala:109)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at org.apache.spark.sql.catalyst.util.CaseInsensitiveMap.foreach(CaseInsensitiveMap.scala:28)
    at org.apache.spark.sql.NullFileFormat.buildReader(NullFileFormat.scala:109)
    at org.apache.spark.sql.execution.datasources.FileFormat$class.buildReaderWithPartitionValues(FileFormat.scala:117)
    at org.apache.spark.sql.NullFileFormat.buildReaderWithPartitionValues(NullFileFormat.scala:47)
    at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD$lzycompute(DataSourceScanExec.scala:285)
    at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD(DataSourceScanExec.scala:283)
    at org.apache.spark.sql.execution.FileSourceScanExec.inputRDDs(DataSourceScanExec.scala:303)
    at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:386)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
    at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)

**Comment by petro-rudenko** [comment]
Same here:
```
 ----- Null Source/Sink options (all lower caps) -----
 path : /sql2
 payloadsize : 4096
 intrange : 19200000
 inputrows : 200000
 schema : intwithpayload
 tasks : 96
...
Caused by: java.lang.Exception: Illegal option : tasks , valid options are: Set(path, payloadsize, intrange, inputrows, rowbuffersz, schema)
        at org.apache.spark.sql.NullFileFormat$$anonfun$buildReader$1.apply(NullFileFormat.scala:127)
        at org.apache.spark.sql.NullFileFormat$$anonfun$buildReader$1.apply(NullFileFormat.scala:124)
```

**Comment by animeshtrivedi** [comment]
Hi @petro-rudenko  - you have a different bug. The original bug was about the "path" key which was not set in the valid key options. This was fixed in b1baca7b475f21aab6b71f474139e809b32e5225. 

You are trying to set "tasks" as an option which is not a valid key option. If you are trying to control the number of tasks/files/partition then you have to tell me more how you are trying to generate data? (see the "Current limitation" section in README.md). The Null file format for Spark (or any other for that matter) does not explicitly support number of tasks. It is a Spark's responsibility to generate X number of task (there are multiple ways in Spark to control this based upon your workload) and each one of the X task will write its own file.

**Comment by petro-rudenko** [comment]
Here's how i'm launching equijoin benchmark:
```
bin/spark-submit -v --num-executors 8 --executor-cores 12 --executor-memory 128G --driver-memory 40G --master yarn --class com.ibm.crail.benchmarks.Main sql-benchmarks-1.0.jar -t equiJoin -a save,/xyz -if org.apache.spark.sql.NullFileFormat -of org.apache.spark.sql.NullFileFormat -ifo inputrows,200000,schema,intwithpayload,payloadsize,4096,intrange,19200000,tasks,96 -i /sql,/sql2
```

**Comment by petro-rudenko** [comment]
Ok got it `tasks,96 ` in `-info` parameter

**Comment by animeshtrivedi** [comment]
yes, the benchmark command line seems ok. Because you want to control the number of tasks, i recommend you to generate a small parquet file with 96 partitions (you can use parquet-generator tool from the zrlio repo) in /sql1 and /sql2. Then these files will be used as a mock input but the data will be generated on the fly by the null file format and the options you specified. Does this make sense? 

Since what you are trying to do is a frequent use-case, I will try to think how to integrate this cleanly in the sql-benchmarks so that people don't have to do hacks like the one I described above. Let me know if you need help to set things/run benchmarks.

**Comment by animeshtrivedi** [comment]
i am going to close this bug report as this is fixed. For further discussion for any of these issues please post at https://groups.google.com/forum/#!forum/zrlio-users  so that others can also benefit from the discussion.
